version: "3.8"
services:
  mariadb:
    env_file: ./.env
    image: "mariadb:latest"
    restart: on-failure
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: codestats
  codestats-server:
    depends_on:
      - mariadb
    build: .
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mariadb://mariadb:3306/codestats",
        "spring.datasource.username" : "${MARIADB_USER}",
        "spring.datasource.password" : "${MARIADB_PASSWORD}"
      }'
    ports:
      - 8080:8080
    restart: on-failure
volumes:
  dbdata:

