INSERT INTO prog_language(language_name) VALUES('TypeScript')
INSERT INTO prog_language(language_name) VALUES('Python')
INSERT INTO prog_language(language_name) VALUES('Ruby')

INSERT INTO language_usage_bytes(language_id, bytes) VALUES(3, 30)
INSERT INTO language_usage_bytes(language_id, bytes) VALUES(2, 10)
INSERT INTO language_usage_bytes(language_id, bytes) VALUES(3, 20)
INSERT INTO language_usage_bytes(language_id, bytes) VALUES(1, 10)
INSERT INTO language_usage_bytes(language_id, bytes) VALUES(1, 10)
INSERT INTO language_usage_bytes(language_id, bytes) VALUES(2, 20)
