INSERT INTO repository(github_id) VALUES(1)
INSERT INTO repository(github_id) VALUES(2)
INSERT INTO repository(github_id) VALUES(3)
INSERT INTO repository(github_id) VALUES(4)
INSERT INTO repository(github_id) VALUES(5)
INSERT INTO repository(github_id) VALUES(6)

INSERT INTO prog_language(language_name) VALUES('TypeScript')
INSERT INTO prog_language(language_name) VALUES('Python')
INSERT INTO prog_language(language_name) VALUES('Ruby')

INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(1, 3, 30)
INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(1, 2, 10)
INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(2, 3, 20)
INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(2, 1, 10)
INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(2, 1, 10)
INSERT INTO language_usage_bytes(repository_id, language_id, bytes) VALUES(2, 2, 20)
